[general]
# import = ["~/.config/alacritty/aman.toml"]
live_config_reload= true

[window]
opacity = 0.9
blur = true

[window.padding]
x = 1
y = 0

[font]
size = 9
normal = { family = "JetBrainsMono", style = "SemiBold" }
# bold_italic = { family = "NotoSansTifinagh", style = "SemiBold" }


[colors]
draw_bold_text_with_bright_colors = true

[cursor]
blink_interval = 750
thickness = 0.15
unfocused_hollow = false

[cursor.style]
blinking = "Never"
shape = "Underline"

