nitrogen --restore &
udiskie &
picom &
syncthing -no-browser &
xrdb -load $XDG_CONFIG_HOME/X11/xresources &
xset r rate 200 35 &
systemctl --user start mpd &
dwmblocks &

dbus-update-activation-environment --all &
gnome-keyring-daemon --start --components=secrets &

exec dwm
