let mapleader=" "

if has('termguicolors')
  set termguicolors
endif
set t_Co=256
syntax on
filetype plugin indent on
colorscheme onedark

" this fix some delay after pressing <Esc> 
set ttimeout
set ttimeoutlen=1
set updatetime=100
set scrolloff=4

" Better editor UI
set number relativenumber
set cursorline

" Better editing experience
set expandtab 
set smarttab
set tabstop=2
set shiftwidth=2
set softtabstop=-1
set autoindent
set smartindent
set wrap
"set list

set clipboard=unnamedplus

" Search behavior
set ignorecase
set smartcase 
set incsearch
set nohlsearch


set wildmode=longest,list,full
set path+=**
set wildmenu

" auto completion mechanism
set nocompatible
set complete+=kspell
set completeopt=menu,menuone,longest,preview,popup

" Folding mechanism
set fillchars=fold:\ 
set foldmethod=indent
set nofoldenable
set foldlevel=99

set shortmess+=cW

" toggle cursor [Normal/Insert] mode
let &t_SI="\e[6 q"
let &t_EI="\e[2 q"
set ttyfast

let g:fzf_layout = { 'window': { 'width': 0.9, 'height': 0.6 } }
